channels:
  - conda-forge
  - defaults
dependencies:
  - libgcc-ng
  - armadillo=10.6.2
  - ccache>=4.3
  - clang-tools=16.0.6
  - clang=16.0.6
  - jemalloc>=5.2.1
  - libta-lib=0.4.0
  - libunwind=1.5.0
  - openblas=0.3.21
  - pip>=23.0.1
  - python>=3.10.0,<3.11.0
  - ta-lib=0.4.19
  - zlib>=1.2.0
  - zstd>=1.5.0
  - pip:
    - black==24.10.0
    - click==8.1.0
    - cython==0.29.24
    - isort==5.9.3
    - joblib==1.2.0
    - lightgbm==3.2.1
    - matplotlib>=3.4.3
    - numba==0.56.4
    - numpy==1.23.5
    - pandas==2.2.2
    - pathos>=0.2.9
    - pre-commit==2.15.0
    - psutil==5.8.0
    - pyarrow>=11.0.0
    - pytest==6.2.5
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyyaml==6.0.0
    - scikit-learn>=1.5.0
    - scipy>=1.10.0
    - seaborn>=0.11.2
    - sexpdata==0.0.3
    - sortedcontainers==2.4.0
    - statsmodels==0.13.2
    - tabulate==0.8.9
    - threadpoolctl==3.1.0
    - torch>=1.13.1,<2.4.0
    - tqdm==4.62.3
    - tsfresh>=0.20.2
    - xarray>=2023.3.0
    - xgboost==1.5.2
    - dask[dataframe]>=2024.5.1
