py_library(
    name = "yang",
    deps = [
        "//python/src/yang/cli",
        "//python/src/yang/data",
        "//python/src/yang/math",
        "//python/src/yang/sim",
        "//python/src/yang/util",
    ],
    visibility = ["//visibility:public"],
)
