data:
  #target: grf_coint_y_ret/y_ret_1__csi500_addlimit
  target: ext/fret_pr_raw_1__csi500_addlimit
  target_len: 1
  features: []
  min_valid_ratio: 0.5
  roll_years:
    train: 4
    valid: 0
    pred: 1

preprocess:
  features:
    - type: CsStdScaler
      center: true
    - type: FillNA
      fill_value: 0

model:
  type: prophet.ml.MLPRegressor
  hidden_layer_sizes: [16, 16, 8, 8]
  activation: "relu"
  solver: "adam"
  alpha: 0.0002
  learning_rate_init: 0.0002
  max_iter: 80
